import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mockControls: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    left: 16,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
    gap: 8,
    zIndex: 110,
    borderRadius: 40,
    paddingHorizontal: 6,
    paddingVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  mockButton: {
    height: 48,
    minWidth: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
    paddingHorizontal: 16,
    borderWidth: 1,
  },
  mockIconButton: {
    height: 48,
    width: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
  },
  mockButtonPrimary: {
    height: 48,
    width: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
  },
  mockButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
});
